# Generated by Django 4.1.4 on 2022-12-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='id',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='my_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
