# Generated by Django 4.1.4 on 2022-12-25 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_todoitem_id_todoitem_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='my_id',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
